name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install MinGW
      - name: Install MinGW
        run: choco install mingw

      # Step 3: Compile the program
      - name: Build Executable
        run: |
          gcc -o webhook_send.exe webhook_send.c -L. -lcurl -lws2_32 -lwldap32


      - name: test
        run: .\webhook_send.exe

      # Step 4: Package the executable with the DLL
      - name: Bundle Executable and DLL
        run: |
          mkdir build
          mv webhook_send.exe build/
          cp libcurl.dll build/

      # Step 5: Upload the bundled files as an artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: webhook-send-bundle
          path: build/
